### PR TITLE
CSIP requirements fix

### PR DESCRIPTION
**Pull request by dockmd**
Fixing many issues detected during validating against corpus: #44 #45 #46 #47 

However issue #44 rule 3 and 4 and issue #45 rule 2 requires more attention, because they cannot be fixed simply by creating a proper schematron test.

### CODE REVIEW

**Comment by Sunday-Crunk** [comment]
## CSIP1: The validator does not check if the OBJID is empty

### Test
```
eark-validator eark-ip-test-corpus/corpus/CSIP/CSIP1/invalid/mets-xml_mets_OBJID_attribute_value_empty/
```

### Result prepatch
Fail: No entry in the schematron results array for CSIP1 despite missing @OBJID

### Fix result
Pass: Missing OBJID error correctly reported

```json
{
  "rule_id": "CSIP1",
  "severity": "Error",
  "location": {
    "context": "/mets:mets",
    "test": "@OBJID != ''",
    "description": "/*[local-name()='mets' and namespace-uri()='http://www.loc.gov/METS/']"
  },
  "message": "The mets/@OBJID attribute is mandatory, its value is a string identifier for the METS document. For the package METS document, this should be the name/ID of the package, i.e. the name of the package root folder. For a representation level METS document this value records the name/ID of the representation, i.e. the name of the top-level representation folder."
}
```

### Test
```
eark-validator eark-ip-test-corpus/corpus/CSIP/CSIP1/valid/minimal_IP_with_1_representation
```

### Result prepatch
Pass: No warning for valid IP METS

### Fix result
Pass: No warning for valid IP METS

## CSIP1: The validator does not check if the OBJID is equal to the name of the representation or package folder

This issue has not been addressed in the fix. As Jakub notes, it's not something that can be asserted in schematron. Consider moving this check into the structural checks.

## CSIP2: The validator does not check if the mets/@type has value from VocabularyContentCategory

### Test
```
eark-validator eark-ip-test-corpus/corpus/CSIP/CSIP2/invalid/mets-xml_mets_TYPE_attribute_value_incorrect
```

### Result prepatch
Fail: No warning for incorrect TYPE attribute value.

### Fix result
Pass: Incorrect type value correctly caught

```json
{
  "rule_id": "CSIP2",
  "severity": "Error",
  "location": {
    "context": "/mets:mets",
    "test": "((@TYPE = 'Textual works – Print') or (@TYPE = 'Textual works – Digital') or (@TYPE = 'Textual works – Electronic Serials') or (@TYPE = 'Digital Musical Composition (score-based representations)') or (@TYPE = 'Musical Scores - Print') or (@TYPE = 'Musical Scores - Digital') or (@TYPE = 'Photographs – Print') or (@TYPE = 'Photographs – Digital') or (@TYPE = 'Other Graphic Images – Print') or (@TYPE = 'Other Graphic Images – Digital') or (@TYPE = 'Microforms') or (@TYPE = 'Audio – On Tangible Medium (digital or analog)') or (@TYPE = 'Audio – Media-independent (digital)') or (@TYPE = 'Motion Pictures – Digital and Physical Media') or (@TYPE = 'Video – File-based and Physical Media') or (@TYPE = 'Software') or (@TYPE = 'Software and Video Games') or (@TYPE = 'Email') or (@TYPE = 'Datasets') or (@TYPE = 'Geospatial Data') or (@TYPE = 'Geographic Information System (GIS) - Vector Data') or (@TYPE = 'GIS Raster and Georeferenced Images') or (@TYPE = 'GIS Vector and Raster Combined') or (@TYPE = 'Non-GIS Cartographic') or (@TYPE = '2D and 3D Computer Aided Design') or (@TYPE = 'Design (schematics, architectural drawings) - Print') or (@TYPE = 'Scanned 3D Objects (output from photogrammetry scanning)') or (@TYPE = 'Databases') or (@TYPE = 'Websites') or (@TYPE = 'Web Archives') or (@TYPE = 'Collection') or (@TYPE = 'Event') or (@TYPE = 'Image') or (@TYPE = 'Interactive resource') or (@TYPE = 'Moving image') or (@TYPE = 'Sound') or (@TYPE = 'Still image') or (@TYPE = 'Text') or (@TYPE = 'Physical object') or (@TYPE = 'Service') or (@TYPE = 'Mixed') or (@TYPE = 'Other')) and (@TYPE != 'Other' or (@TYPE = 'Other' and @csip:OTHERTYPE != ''))",
    "description": "/*[local-name()='mets' and namespace-uri()='http://www.loc.gov/METS/']"
  },
  "message": "The `mets/@TYPE` attribute MUST be used to declare the category of the content held in the package, e.g. \"Datasets\", \"Websites\", \"Mixes\" , \"Other\", etc.. Legal values are defined in a fixed vocabulary. When the content category used falls outside of the defined vocabulary the `mets/@TYPE` value must be set to \"OTHER\" and the specific value declared in `mets/@csip:OTHERTYPE`. The vocabulary will develop under the curation of the DILCIS Board as additional content information type specifications are produced."
}
```

### Test
```
eark-validator eark-ip-test-corpus/corpus/CSIP/CSIP2/valid/minimal_IP_with_1_representation
```

### Result prepatch
Pass: No warning

### Fix result
Pass: No warning

## CSIP2: The validator does not check if mets/@csip:OTHERTYPE exists when mets/@type = "OTHER"

### Test
```
eark-validator eark-ip-test-corpus/corpus/CSIP/CSIP2/invalid/mets-xml_mets_TYPE_attribute_value_OTHER_and_csip-OTHERTYPE_attribute_not_exist
```

### Result prepatch
Fail: No warning

### Fix result
Pass: Missing OTHERTYPE attribute caught

```json
{
  "rule_id": "CSIP2",
  "severity": "Error",
  "location": {
    "context": "/mets:mets",
    "test": "((@TYPE = 'Textual works – Print') or (@TYPE = 'Textual works – Digital') or (@TYPE = 'Textual works – Electronic Serials') or (@TYPE = 'Digital Musical Composition (score-based representations)') or (@TYPE = 'Musical Scores - Print') or (@TYPE = 'Musical Scores - Digital') or (@TYPE = 'Photographs – Print') or (@TYPE = 'Photographs – Digital') or (@TYPE = 'Other Graphic Images – Print') or (@TYPE = 'Other Graphic Images – Digital') or (@TYPE = 'Microforms') or (@TYPE = 'Audio – On Tangible Medium (digital or analog)') or (@TYPE = 'Audio – Media-independent (digital)') or (@TYPE = 'Motion Pictures – Digital and Physical Media') or (@TYPE = 'Video – File-based and Physical Media') or (@TYPE = 'Software') or (@TYPE = 'Software and Video Games') or (@TYPE = 'Email') or (@TYPE = 'Datasets') or (@TYPE = 'Geospatial Data') or (@TYPE = 'Geographic Information System (GIS) - Vector Data') or (@TYPE = 'GIS Raster and Georeferenced Images') or (@TYPE = 'GIS Vector and Raster Combined') or (@TYPE = 'Non-GIS Cartographic') or (@TYPE = '2D and 3D Computer Aided Design') or (@TYPE = 'Design (schematics, architectural drawings) - Print') or (@TYPE = 'Scanned 3D Objects (output from photogrammetry scanning)') or (@TYPE = 'Databases') or (@TYPE = 'Websites') or (@TYPE = 'Web Archives') or (@TYPE = 'Collection') or (@TYPE = 'Event') or (@TYPE = 'Image') or (@TYPE = 'Interactive resource') or (@TYPE = 'Moving image') or (@TYPE = 'Sound') or (@TYPE = 'Still image') or (@TYPE = 'Text') or (@TYPE = 'Physical object') or (@TYPE = 'Service') or (@TYPE = 'Mixed') or (@TYPE = 'Other')) and (@TYPE != 'Other' or (@TYPE = 'Other' and @csip:OTHERTYPE != ''))",
    "description": "/*[local-name()='mets' and namespace-uri()='http://www.loc.gov/METS/']"
  },
  "message": "The `mets/@TYPE` attribute MUST be used to declare the category of the content held in the package, e.g. \"Datasets\", \"Websites\", \"Mixes\" , \"Other\", etc.. Legal values are defined in a fixed vocabulary. When the content category used falls outside of the defined vocabulary the `mets/@TYPE` value must be set to \"OTHER\" and the specific value declared in `mets/@csip:OTHERTYPE`. The vocabulary will develop under the curation of the DILCIS Board as additional content information type specifications are produced."
}
```

Note: There is an incongruity between CSIP2 and CSIP3 tests due to a casing issue. We cannot satisfy both at once with the same test package. All further test corpus packages that use @TYPE=OTHER fail CSIP2 in tests moving forward.

## CSIP2: The validator does not check if mets/@csip:OTHERTYPE is set to some value when mets/@type = "OTHER"

### Test
```
eark-validator eark-ip-test-corpus/corpus/CSIP/CSIP2/invalid/mets-xml_mets_TYPE_attribute_value_OTHER_and_csip-OTHERTYPE_attribute_has_no_value
```

### Result prepatch
Fail: No warning

### Fix result
Fail*: CSIP2 throws an error warning, but only because it fails the TYPE vocab check. The value in the METS is "OTHER" while the schematron checks for "Other" per the vocabulary. 

## CSIP4: The validator does not check if the mets/@CONTENTINFORMATIONTYPE has value from VocabularyContentInformationTypeSpecification

### Test
```
eark-validator eark-ip-test-corpus/corpus/CSIP/CSIP4/invalid/CONTENTINFORMATIONTYPE_value_incorrect
```

### Result prepatch
Fail: Not caught by schematron rule but is caught by the schema itself

### Fix result
Pass: Correctly caught invalid CONTENTINFORMATIONTYPE value not from vocab

```json
{
  "rule_id": "CSIP4",
  "severity": "Error",
  "location": {
    "context": "/mets:mets",
    "test": "((@csip:CONTENTINFORMATIONTYPE = 'ERMS') or (@csip:CONTENTINFORMATIONTYPE = 'SIARD1') or (@csip:CONTENTINFORMATIONTYPE = 'SIARD2') or (@csip:CONTENTINFORMATIONTYPE = 'SIARDDK') or (@csip:CONTENTINFORMATIONTYPE = 'GeoData') or (@csip:CONTENTINFORMATIONTYPE = 'citscarchival_v1_0') or (@csip:CONTENTINFORMATIONTYPE = 'cscarchival_v1_0') or (@csip:CONTENTINFORMATIONTYPE = 'citserms_v2_1') or (@csip:CONTENTINFORMATIONTYPE = 'citserms_v3_0') or (@csip:CONTENTINFORMATIONTYPE = 'citspremis_v1_0') or (@csip:CONTENTINFORMATIONTYPE = 'cspremis_v1_0') or (@csip:CONTENTINFORMATIONTYPE = 'citsehpj_v1_0') or (@csip:CONTENTINFORMATIONTYPE = 'citsehpj_v2_0') or (@csip:CONTENTINFORMATIONTYPE = 'citsehcr_v1_0') or (@csip:CONTENTINFORMATIONTYPE = 'citssiard_v1_0') or (@csip:CONTENTINFORMATIONTYPE = 'citsgeospatial_v3_0') or (@csip:CONTENTINFORMATIONTYPE = 'MIXED') or (@csip:CONTENTINFORMATIONTYPE = 'OTHER')) and (@csip:CONTENTINFORMATIONTYPE != 'Other' or (@csip:CONTENTINFORMATIONTYPE = 'Other' and @csip:OTHERCONTENTINFORMATIONTYPE != ''))",
    "description": "/*[local-name()='mets' and namespace-uri()='http://www.loc.gov/METS/']"
  },
  "message": "Used to declare the Content Information Type Specification used when creating the package. Legal values are defined in a fixed vocabulary. The attribute is mandatory for representation level METS documents."
}
```

### Test
```
eark-validator eark-ip-test-corpus/corpus/CSIP/CSIP4/valid/valid_IP_with_SHOULD_MAY_1_rep
```

### Result prepatch
Pass: No warning

### Fix result
Pass: No warning

## CSIP4: The validator does not check if mets/@csip:OTHERCONTENTINFORMATIONTYP exists when mets/@CONTENTINFORMATIONTYPE = "OTHER"

### Test
```
eark-validator eark-ip-test-corpus/corpus/CSIP/CSIP4/invalid/CONTENTINFORMATIONTYPE_OTHER_and_OTHERCONTENTINFORMATIONTYPE_not_exist
```

### Result prepatch
Fail: No warning

### Fix result
Fail*: Test package uses type "OTHER" not type "Other". This is because of the casing inconsistency. With the value "Other", it works correctly.

## CSIP4: The validator does not check if mets/@csip:OTHERCONTENTINFORMATIONTYPE is set to some value when mets/@CONTENTINFORMATIONTYPE = "OTHER"

### Result prepatch
Fail: No warning

### Fix result
Fail*: Same issue as above.

## CSIP9: The validator does not check if the mets/metsHdr/@csip:OAISPACKAGETYPE has value from VocabularyOAISPackageType

### Test
```
eark-validator eark-ip-test-corpus/corpus/CSIP/CSIP9/invalid/mets-xml_metsHdr_OAISPACKAGETYPE_attribute_value_incorrect
```

### Result prepatch
Fail: No warning, schema catches it

### Fix result
Pass: Catches warning, but the message could be more descriptive

## Additional Notes
- CSIP1 test related to matching attributes to filesystem names can't be addressed in schematron, could we consider moving it to code? @carlwilson 
- CSIP2 and CSIP4 tests related to "OTHER" type and corresponding "OTHERTYPE" attribute are failing due to casing issues (OTHER vs Other), but as @dockmd notes this is really a problem between the spec, the vocabulary and the test corpus rather than the validator.  This needs to be standardized across the specifications and implementations.
- Consider making error message more descriptive for CSIP9, but again of course that is non-trivial.
- CSIP2 and 3 have redundant crossover which can make parsing validation results confusing, same as above though since both requirements describe enough scope to warrant comprehensive validation of the OTHERTYPE attribute individually.

**Comment by carlwilson** [comment]
Many thanks @Sunday-Crunk that's a better job than I could have done.

**Comment by dockmd** [comment]
Thanks for testing @Sunday-Crunk, great find with 'Other' inconsistency. I think we should stick to values defined in vocabulary as otherwise testing if value belongs to vocabulary would always fail. I've fixed CSIP 2, 3 and 4  - 'Other' issue and created [PR](https://github.com/DILCISBoard/eark-ip-test-corpus/pull/495) as testcase needed adjustments too.

Also I've fixed more issues: #49 #50 #51 #52 #53 #57 #59

**Comment by Sunday-Crunk** [comment]
@dockmd @carlwilson I've switched to putting my notes on the commits, couple of things to check in CSIP20, 24 and 40, other than that all seems great

**Review by carlwilson — APPROVED** [review]

**Comment by Sunday-Crunk** [comment]
@carlwilson Did you see my note about the CSIP20 change?

**Comment by dockmd** [comment]
@Sunday-Crunk @carlwilson 
Good finding with the status warning behaviour. Fixed so that when status is not present, a warning will be generated, but when it is present but with an invalid value, an error will be generated. The same applies for CSIP34 and CSIP47 (#61). Also it required CSIP20 testcase fix - https://github.com/DILCISBoard/eark-ip-test-corpus/pull/496

**Pull request merged**
