### PR TITLE
REFACT: Project build to pyproject.toml

### PR DESCRIPTION
**Pull request by carlwilson**
- updated project build to use [`pyproject.toml`](https://packaging.python.org/en/latest/flow/#the-configuration-file) instead of `setup.py`;
- transferred previous build parameters from `setup.py` to `pyproject.toml`;
- added versioning via <https://setuptools-git-versioning.readthedocs.io/en/stable/index.html>;
  - base development version is currently `0.3.0` while testing the release process;
  - the development version scheme is based on: <https://setuptools-git-versioning.readthedocs.io/en/stable/schemas/file/version_file.html>;
  - using a variation of this to create development versions for PyPI Test: <https://setuptools-git-versioning.readthedocs.io/en/stable/schemas/file/dev_release_file.html>;
  - the version template for the dynamic version is `"{tag}.dev{env:GITHUB_RUN_NUMBER:{ccount}}"`, see <https://setuptools-git-versioning.readthedocs.io/en/stable/substitutions/index.html> for template details;
- added LICENSE file with Apache 2.0 license for reference from `pyproject.toml`;
- removed `setup.py`; and
- added `.vscode/` to `.gitignore`.

### CODE REVIEW

**Comment by scfkmd** [comment]
@carlwilson 
I have tried checking out the code on a shorter path in Windows. 
It seems to be problems with the colon ":" character under tests, as this is a prohibited char in win.

Can we do something about this?

z6scf@A51845 MINGW64 /c/E-Ark
$ git clone https://github.com/carlwilson/py-eark-ip-validator.git
Cloning into 'py-eark-ip-validator'...
remote: Enumerating objects: 931, done.
remote: Counting objects: 100% (931/931), done.
remote: Compressing objects: 100% (351/351), done.
remote: Total 931 (delta 548), reused 899 (delta 516), pack-reused 0
Receiving objects: 100% (931/931), 615.25 KiB | 3.38 MiB/s, done.
Resolving deltas: 100% (548/548), done.
z6scf@A51845 MINGW64 /c/E-Ark
$ cd py-eark-ip-validator/

z6scf@A51845 MINGW64 /c/E-Ark/py-eark-ip-validator (main)
$ git branch -a
* main
  remotes/origin/HEAD -> origin/main
  remotes/origin/app/corpus-validator
  remotes/origin/feat/autospec
  remotes/origin/feat/corpus-reporting
  remotes/origin/feat/gh-actions-build
  remotes/origin/main
  remotes/origin/refact/cli
  remotes/origin/refact/model
  remotes/origin/refact/python-build
  remotes/origin/refact/typesafety
  remotes/origin/refact/validators

z6scf@A51845 MINGW64 /c/E-Ark/py-eark-ip-validator (main)
$ git checkout --track origin/refact/python-build
error: invalid path 'tests/resources/ips/unpacked/733dc055-34be-4260-85c7-5549a7083031-bad/metadata/preservation/urn:roda:premis:event:3c0e58e4-e76e-4029-8625-c7fb20985933.xml'
error: invalid path 'tests/resources/ips/unpacked/733dc055-34be-4260-85c7-5549a7083031-bad/metadata/preservation/urn:roda:premis:event:3e281637-0499-4a75-898d-a0495ec482cd.xml'
error: invalid path 'tests/resources/ips/unpacked/733dc055-34be-4260-85c7-5549a7083031-bad/metadata/preservation/urn:roda:premis:event:3f415e20-5148-4d09-850b-5dcfb5c524f5.xml'
error: invalid path 'tests/resources/ips/unpacked/733dc055-34be-4260-85c7-5549a7083031-bad/metadata/preservation/urn:roda:premis:event:771e6d74-ce9e-40cc-8b8b-18e1f792397f.xml'
error: invalid path 'tests/resources/ips/unpacked/733dc055-34be-4260-85c7-5549a7083031-bad/metadata/preservation/urn:roda:premis:event:a7826c53-cf4b-4e93-baa4-9e74cdc159fc.xml'
error: invalid path 'tests/resources/ips/unpacked/733dc055-34be-4260-85c7-5549a7083031-bad/metadata/preservation/urn:roda:premis:event:a9399785-fbdc-43a5-b3fc-b0a9826e2082.xml'
error: invalid path 'tests/resources/ips/unpacked/733dc055-34be-4260-85c7-5549a7083031-bad/metadata/preservation/urn:roda:premis:event:c6308cdb-2696-4431-9572-4322ae9f1bdc.xml'
error: invalid path 'tests/resources/ips/unpacked/733dc055-34be-4260-85c7-5549a7083031-bad/metadata/preservation/urn:roda:premis:event:e476189a-3403-426f-9a8b-5823e3850f83.xml'
error: invalid path 'tests/resources/ips/unpacked/733dc055-34be-4260-85c7-5549a7083031-bad/metadata/preservation/urn:roda:premis:event:f01528c6-0a01-40d3-abcf-bdbf611837da.xml'
error: invalid path 'tests/resources/ips/unpacked/733dc055-34be-4260-85c7-5549a7083031-bad/metadata/preservation/urn:roda:premis:event:f6cae1e0-2c38-408c-a31a-8854118bd77b.xml'
error: invalid path 'tests/resources/ips/unpacked/733dc055-34be-4260-85c7-5549a7083031-bad/representations/rep1/metadata/preservation/urn:roda:premis:file:RODA-in.png.xml'
error: invalid path 'tests/resources/ips/unpacked/733dc055-34be-4260-85c7-5549a7083031-bad/representations/rep1/metadata/preservation/urn:roda:premis:representation:cfb449b3-ca41-3f81-ba06-bb8f57ee601e.xml'
error: invalid path 'tests/resources/ips/unpacked/733dc055-34be-4260-85c7-5549a7083031/metadata/preservation/urn:roda:premis:event:3c0e58e4-e76e-4029-8625-c7fb20985933.xml'
error: invalid path 'tests/resources/ips/unpacked/733dc055-34be-4260-85c7-5549a7083031/metadata/preservation/urn:roda:premis:event:3e281637-0499-4a75-898d-a0495ec482cd.xml'
error: invalid path 'tests/resources/ips/unpacked/733dc055-34be-4260-85c7-5549a7083031/metadata/preservation/urn:roda:premis:event:3f415e20-5148-4d09-850b-5dcfb5c524f5.xml'
error: invalid path 'tests/resources/ips/unpacked/733dc055-34be-4260-85c7-5549a7083031/metadata/preservation/urn:roda:premis:event:771e6d74-ce9e-40cc-8b8b-18e1f792397f.xml'
error: invalid path 'tests/resources/ips/unpacked/733dc055-34be-4260-85c7-5549a7083031/metadata/preservation/urn:roda:premis:event:a7826c53-cf4b-4e93-baa4-9e74cdc159fc.xml'
error: invalid path 'tests/resources/ips/unpacked/733dc055-34be-4260-85c7-5549a7083031/metadata/preservation/urn:roda:premis:event:a9399785-fbdc-43a5-b3fc-b0a9826e2082.xml'
error: invalid path 'tests/resources/ips/unpacked/733dc055-34be-4260-85c7-5549a7083031/metadata/preservation/urn:roda:premis:event:c6308cdb-2696-4431-9572-4322ae9f1bdc.xml'
error: invalid path 'tests/resources/ips/unpacked/733dc055-34be-4260-85c7-5549a7083031/metadata/preservation/urn:roda:premis:event:e476189a-3403-426f-9a8b-5823e3850f83.xml'
error: invalid path 'tests/resources/ips/unpacked/733dc055-34be-4260-85c7-5549a7083031/metadata/preservation/urn:roda:premis:event:f01528c6-0a01-40d3-abcf-bdbf611837da.xml'
error: invalid path 'tests/resources/ips/unpacked/733dc055-34be-4260-85c7-5549a7083031/metadata/preservation/urn:roda:premis:event:f6cae1e0-2c38-408c-a31a-8854118bd77b.xml'
error: invalid path 'tests/resources/ips/unpacked/733dc055-34be-4260-85c7-5549a7083031/representations/rep1/metadata/preservation/urn:roda:premis:file:RODA-in.png.xml'
error: invalid path 'tests/resources/ips/unpacked/733dc055-34be-4260-85c7-5549a7083031/representations/rep1/metadata/preservation/urn:roda:premis:representation:cfb449b3-ca41-3f81-ba06-bb8f57ee601e.xml'

z6scf@A51845 MINGW64 /c/E-Ark/py-eark-ip-validator (main)

**Comment by carlwilson** [comment]
I think that I should be able to do something about this, it's a far from reliable/elegant solution. Will refactor the tests and push to this branch.

**Comment by carlwilson** [comment]
> Can we do something about this?

I've pushed a fix up @scfkmd that's purged the colons for now.

**Comment by scfkmd** [comment]
I have a few findings based on testing on Windows and a Linux env. 
Maybe we should consider supporting just Linux for the moment being and focus on Windows later on?

Testing on Linux I get the following error from ip-check when running against a .zip and a directory (similar results):

```
(venv) scf@ark-eark01:~/py-eark-ip-validator$ ip-check ../mets-xml_metsHdr_agent_note_NOTETYPE_valid.zip
Traceback (most recent call last):
  File "/home/UVD/scf/py-eark-ip-validator/venv/bin/ip-check", line 5, in <module>
    from ip_validation.cli.app import main
  File "/home/UVD/scf/py-eark-ip-validator/venv/lib/python3.10/site-packages/ip_validation/cli/app.py", line 34, in <module>
    import ip_validation.infopacks.structure as STRUCT
ModuleNotFoundError: No module named 'ip_validation.infopacks.structure'
```

Testing on Windows I had to setup and run the virtual environment in a different way:

```
pip install virtualenv
virtualenv --python C:\Path\To\Python\python.exe venv
.\venv\Scripts\activate
```

Running the ip-check on Windows gave me this error:

(venv) [path to validator]\py-eark-ip-validator>ip-check mets-xml_metsHdr_agent_note_NOTETYPE_valid.zip
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "[path to validator]\py-eark-ip-validator\venv\Scripts\ip-check.exe\__main__.py", line 4, in <module>
  File "[path to validator]\py-eark-ip-validator\venv\Lib\site-packages\ip_validation\cli\app.py", line 34, in <module>
    import ip_validation.structure as STRUCT
  File "[path to validator]\py-eark-ip-validator\venv\Lib\site-packages\ip_validation\structure.py", line 32, in <module>
    from ip_validation.rules import Severity
  File "[path to validator]\py-eark-ip-validator\venv\Lib\site-packages\ip_validation\rules.py", line 33, in <module>
    from ip_validation.specifications.specification import EarkSpecifications, Specification
  File "[path to validator]\py-eark-ip-validator\venv\Lib\site-packages\ip_validation\specifications\specification.py", line 33, in <module>
    from ip_validation.xml.schema import METS_PROF_SCHEMA
  File "[path to validator]\py-eark-ip-validator\venv\Lib\site-packages\ip_validation\xml\schema.py", line 35, in <module>
    'csip': etree.XMLSchema(file=str(files(SCHEMA).joinpath('mets.csip.local.v2-0.xsd'))),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src\lxml\xmlschema.pxi", line 89, in lxml.etree.XMLSchema.__init__
lxml.etree.XMLSchemaParseError: Failed to locate the main schema resource at '[path to validator]\py-eark-ip-validator\venv\Lib\site-packages\ip_validation\xml\resources\schema\mets.csip.local.v2-0.xsd'.

**Comment by carlwilson** [comment]
@scfkmd Sorry, I should have seen this earlier. Don't get too concerned about those results, I know that some of that is broken after I brutally refactored for unit testability. I have further PR branches stacked that will fix these as we go sorry. For now you should only worry if the build and pytests fail.

Apologies.

**Pull request merged**
